# Generated by Django 5.1.6 on 2025-02-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, max_length=20, upload_to='media/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
